config/routes.rb
Rails.application.routes.draw do
  get 'admin_pages/index'

  get '/mypages' => 'mypages#index'
  get '/mypages/edit'

  get 'admin_pages/index2', as: 'admin_pages_index2'
  post 'admin_pages/search'

  resources :question2s
  resources :question3s
  resources :admin_pages

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mypages#index'
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
   before_action  :authenticate_admin!
#  layout 'admin'

   protect_from_forgery except: :destroy # destroyアクションを除外

  def index
    @user_datas = Question2.all
  end

  def index2
      @user_datas = Question2.all
  end

  def edit
    @user_data = Question2.find(params[:id])
  end

  def update
    q2 = Question2.find_by(user_id:params[:question2][:user_id])
    q2.update_attributes(question2s_params)
    redirect_to admin_pages_path
  end

  def destroy
    Question2.delete(params[:id])
    redirect_to admin_pages_index_path
  end

  def search
    name = params[:serach_name]
    q = Question2.where(firstName: name).or(Question2.where(lastName: name))
    if name == ""
      @user_datas = Question2.all
    else
      @user_datas = q
    end
    render admin_pages_index_path
  end

  private
  def question2s_params
    params.require(:question2).permit(
      :phone_number, :postal_code, :address, :prefecture,
      :age, :gender, :car_type, :model_year, :color, :licence_type,
      :user_id, :length_of_service, :employee, :job, :skill,
      :is_consul, :is_wrapping, :lastName, :firstName, :mobileOS, :address2,
      :carAddress, :isDriveRecorder
    )
  end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/_search.html.erb
<div id="search-zone">
  <%= form_tag '/admin_pages/search', method: :post do %>
  <%= label_tag '名前' %>
  <%= text_field_tag :serach_name %>
  <%= submit_tag '送信' %>
  <%end%>
</div>

app/views/admin_pages/edit.html.erb
<div id='user_data_edit' >
<h1>個別データ編集ページ</h1>
<%= form_for @user_data, :url => { :controller => :admin_pages, :action => :update } do |f| %>
  <%= f.hidden_field :user_id, value: @user_data.user_id %>
  <div id='LV1' style="float:left">
  <div class='form_area'>
    <%= f.label '性' %>
    <%= f.text_field :firstName %>
  </div>

  <div class='form_area'>
    <%= f.label '名' %>
    <%= f.text_field :lastName %>
  </div>

  <div class='form_area'>
    <%= f.label 'TEL' %>
    <%= f.text_field :phone_number %>
  </div>

  <div class='form_area'>
    <%= f.label '郵便番号' %>
    <%= f.text_field :postal_code %>
  </div>

  <div class='form_area'>
    <%= f.label '県' %>
    <%= f.select :prefecture, Question2.prefecture_lists.keys %>
  </div>

  <div class='form_area'>
    <%= f.label '市' %>
    <%= f.text_field :address %>
  </div>

  <div class='form_area'>
    <%= f.label '区' %>
    <%= f.text_field :address2 %>
  </div>

  <div class='form_area'>
    <%= f.label '年齢' %>
    <%= f.select :age, Question2::AGE_LISTS %>
  </div>

  <div class='form_area'>
    <%= f.label '性別' %>
    <%= f.select :gender, Question2.gender_lists.keys %>
  </div>

  <div class='form_area'>
    <%= f.label '車種' %>
    <%= f.text_field :car_type %>
  </div>

  <div class='form_area'>
    <%= f.label '年式' %>
    <%= f.text_field :model_year %>
  </div>

  <div class='form_area'>
    <%= f.label '車両の色' %>
    <%= f.text_field :color %>
  </div>

  <div class='form_area'>
    <%= f.label '車庫証明の住所' %>
    <%= f.text_field :carAddress %>
  </div>

  <div class='form_area'>
    <%= f.label '免許証の色' %>
    <%= f.select :licence_type, Question2.licenceType_lists.keys %>
  </div>

  <div class='form_area'>
    <%= f.label 'モバイルのOS' %>
    <%= f.select :mobileOS, Question2.mobileOS_lists.keys %>
  </div>
</div>

<div id='LV2'>
  <div class='form_area'>
    <%= f.label 'ドライブレコーダー' %>
    <%= f.select :isDriveRecorder, [['搭載',true],['非搭載',false]] %>
  </div>

  <div class='form_area'>
    <%= f.label '現在の職場の勤続年数' %>
    <%= f.text_field :length_of_service %>
  </div>

  <div class='form_area'>
    <%= f.label '事業所（会社）の従業員数' %>
    <%= f.select :employee, Question2.employeesNum_lists.keys %>
  </div>

  <div class='form_area'>
    <%= f.label '職業' %>
    <%= f.text_area :skill, rows:14 %>
  </div>

  <div class='form_area'>
    <%= f.label 'スポットワークの依頼を受けるか' %>
    <%= f.select :is_consul, [['はい', true],['いいえ', false]] %>
  </div>

  <div class='form_area'>
    <%= f.label 'ラッピング作業を自分で行う意思があるか' %>
    <%= f.select :is_wrapping, [['はい', true],['いいえ', false]] %>
  </div>
</div>
<!--end of LV2-->
  <div class='submit_area'>
    <%= f.submit '更新' %>
    <%= link_to "キャンセル", admin_pages_path %>
  </div>

<%end%>
</div>

app/views/admin_pages/index.html.erb
<div>
  <h1>管理者ページ</h1>
  <h2><%= link_to 'LV2のページ情報へ', admin_pages_index2_path %></h2>
  <div>
    <%= render :partial => 'search' %>
    <table class="table table-hover">
      </tbody>
        <tr>
          <th>ID</th>
          <th>性</th>
          <th>名</th>
          <th>TEL</th>
          <th>郵便番号</th>
          <th>県</th>
          <th>市</th>
          <th>区</th>
          <th>年齢</th>
          <th>性別</th>
          <th>車種</th>
          <th>年式</th>
          <th>車両の色</th>
          <th>車庫証明の住所</th>
          <th>免許証の色</th>
          <th>モバイルのOS</th>
          <th>ドライブレコーダー</th>
          <th></th>
        </tr>
        <% @user_datas.each do |elem| %>
        <tr>
          <td><%= link_to "#{elem.id}", edit_admin_page_path(id:elem.id) %></td>
          <td><%= elem.firstName %></td>
          <td><%= elem.lastName %></td>
          <td><%= elem.phone_number %></td>
          <td><%= elem.postal_code %></td>
          <td><%= elem.prefecture %></td>
          <td><%= elem.address %></td>
          <td><%= elem.address2 %></td>
          <td><%= elem.age %></td>
          <td><%= elem.gender %></td>
          <td><%= elem.car_type %></td>
          <td><%= elem.model_year %></td>
          <td><%= elem.color %></td>
          <td><%= elem.carAddress %></td>
          <td><%= elem.licence_type %></td>
          <td><%= elem.mobileOS %></td>
          <td><%= convertBoolValueToStr(elem.isDriveRecorder) %></td>
          <td><%= button_to "削除", "admin_pages/#{elem.id}", method: "delete", data: { confirm: "id:#{elem.id}のデータを削除します。\n*削除後データの復元はできません。" } %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/admin_pages/index2.html.erb
<div>
  <h1>管理者ページ</h1>
  <h2><%= link_to 'LV1のページ情報へ', admin_pages_path %></h2>
  <div>
    <%= render :partial => 'search' %>
    <table class="table table-hover">
      </tbody>
        <tr>
          <th>ID</th>
          <th>現在の職場の勤続年数</th>
          <th>事業所（会社）の従業員数</th>
          <th>職業</th>
          <th>持っているスキルや免許</th>
          <th>スポットワークの依頼</th>
          <th>ラッピング作業</th>
          <th></th>
          <th></th>
        </tr>
        <% @user_datas.each do |elem| %>
        <tr>
          <td><%= link_to "#{elem.id}", edit_admin_page_path(id:elem.id) %></td>
          <td><%= elem.length_of_service %></td>
          <td><%= elem.employee %></td>
          <td><%= elem.job %></td>
          <td><%= elem.skill %></td>
          <td><%= convertBoolValueToStr(elem.is_consul) %></td>
          <td><%= convertBoolValueToStr(elem.is_wrapping) %></td>
          <td></td>
          <td><%= button_to "削除", "#{elem.id}", method: "delete", data: { confirm: "id:#{elem.id}のデータを削除します。\n*削除後データの復元はできません。" } %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>